#include<iostream.h>
#include<conio.h>
class distance{
private:
int feet;
float inches;
public:
void getdistance(int,float);
distance.add distance (distance);
void put distance (void);
};
void distance::get distance(int,float)
{
feet=f;
inches=i;
}
distance distance::add distance(d1....d1){
distance d;
d.feet=feet+d2=feet;
if(d.inches=12){
d.inches=12
d.feet++; }
return d;
}
void distance::put distance(void)
{
cout<<"feet"<<feet<<"inches"<<inches<<endl;
}
};
int main()
{
distance d1,d2,d3;
clrscr();
d1.get distance:(11,9,5);
d2.get distance:(5,6,5);
d3.get distance:(d2);

d1.put distance();
d2.put distance();
d3.put distance();

return 0;
}